package cat.copernic.m03uf06review.pojos;
// Generated 10-dic-2020 16:18:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumnat generated by hbm2java
 */
public class Alumnat  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nom;
     private String cognoms;
     private Double matricula;
     private Date dataNaixement;
     private Character familiaNombrosa;
     private Boolean mayorEdad;

    public Alumnat() {
    }

    public Alumnat(String dni, String nom, String cognoms, Double matricula, Date dataNaixement, Character familiaNombrosa, Boolean mayorEdad) {
       this.dni = dni;
       this.nom = nom;
       this.cognoms = cognoms;
       this.matricula = matricula;
       this.dataNaixement = dataNaixement;
       this.familiaNombrosa = familiaNombrosa;
       this.mayorEdad = mayorEdad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCognoms() {
        return this.cognoms;
    }
    
    public void setCognoms(String cognoms) {
        this.cognoms = cognoms;
    }
    public Double getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Double matricula) {
        this.matricula = matricula;
    }
    public Date getDataNaixement() {
        return this.dataNaixement;
    }
    
    public void setDataNaixement(Date dataNaixement) {
        this.dataNaixement = dataNaixement;
    }
    public Character getFamiliaNombrosa() {
        return this.familiaNombrosa;
    }
    
    public void setFamiliaNombrosa(Character familiaNombrosa) {
        this.familiaNombrosa = familiaNombrosa;
    }
    public Boolean getMayorEdad() {
        return this.mayorEdad;
    }
    
    public void setMayorEdad(Boolean mayorEdad) {
        this.mayorEdad = mayorEdad;
    }




}


