package cat.copernic.m03uf06review.pojos;
// Generated 10-dic-2020 16:18:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumnat generated by hbm2java
 */
public class Alumnat  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nom;
     private String cognoms;
     private Double matricula;
     private Date dataNaixement; 
     private Boolean mayorEdad;

    public Alumnat() {
    }

    public Alumnat(Integer id, String dni, String nom, String cognoms, Double matricula, Date dataNaixement, Boolean mayorEdad) {
        this.id = id;
        this.dni = dni;
        this.nom = nom;
        this.cognoms = cognoms;
        this.matricula = matricula;
        this.dataNaixement = dataNaixement;
        this.mayorEdad = mayorEdad;
    }

   

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDni() {
        return dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getCognoms() {
        return cognoms;
    }

    public void setCognoms(String cognoms) {
        this.cognoms = cognoms;
    }

    public Double getMatricula() {
        return matricula;
    }

    public void setMatricula(Double matricula) {
        this.matricula = matricula;
    }

    public Date getDataNaixement() {
        return dataNaixement;
    }

    public void setDataNaixement(Date dataNaixement) {
        this.dataNaixement = dataNaixement;
    }

    public Boolean getMayorEdad() {
        return mayorEdad;
    }

    public void setMayorEdad(Boolean mayorEdad) {
        this.mayorEdad = mayorEdad;
    }

    




}


